### PR TITLE
ROS 2

### PR DESCRIPTION
**Pull request by mhubii**
Refers to #1

### CODE REVIEW

**Comment by mhubii** [comment]
This PR can now be merged @ARoefer. Note, there is no interactive segmentation support via `rqt_image_view_seg`, as mentioned in https://github.com/robot-learning-freiburg/ros_sam/issues/1#issuecomment-1810129817

**Comment by ARoefer** [comment]
@mhubii thank you for this quick PR! I'm afraid I am busy this week, but I'll see that I set up a ROS 2 env next week and try out your PR. One question I already have though: Is it a common convention in ROS 2 to name everything `ros2_*`? I am just asking because this is a rather large name change which might make merging possible updates from the ROS1 version harder later on. But if it is, we will of course stick with it.

**Comment by mhubii** [comment]
No problem, was in need for something similar anyhow. Yes, `ros2_*` is a really common prefix. ROS 1 is eol, so might be easier to not back port indefinitely. No worries at all, please take your time.

Edit: actually not eol, wasn't aware.

**Comment by mhubii** [comment]
Maybe re-target the PR into a dev branch if you are afraid of conflicts. The logic is identical to what is available in ROS 1. Namings can still be changed in the dev branch, but people can already use it without going through forks. Just let me know.

**Comment by mhubii** [comment]
FYI citation is now added

**Comment by mhubii** [comment]
> @mhubii thank you for this quick PR! I'm afraid I am busy this week, but I'll see that I set up a ROS 2 env next week and try out your PR. One question I already have though: Is it a common convention in ROS 2 to name everything `ros2_*`? I am just asking because this is a rather large name change which might make merging possible updates from the ROS1 version harder later on. But if it is, we will of course stick with it.

sorry I tried a little but realized to facilitate ROS 1 / 2 compatibility the ROS 1 branch would require changes first. Hence closing the PR.

**Pull request closed without merging**
